### ISSUE TITLE
Hide DropDown menubar

### ISSUE THREAD

**Issue by alexrmacleod** [nmattisson/DropdownMenu#21]
I use this with a container view to segue between three different collection views. I want to hide the Drop down menu you when scroll up on any of my collection views, and show the dropdown menu when you scroll down? is this possible?

**Comment by nmattisson** [comment]
Hi @alexrmacleod,
Yes, that's possible and there are a few different ways to do it. One way could be to put that logic in an event handler tied to the gesture of scrolling.

**Comment by alexrmacleod** [comment]
i'm a rookie programer what kind of logic are we talking about?, and am using universal size classes with constraints. what do you mean by gesture of scrolling?

**Comment by nmattisson** [comment]
Hi @alexrmacleod, I was referring to gesture controllers in iOS: https://developer.apple.com/library/ios/documentation/EventHandling/Conceptual/EventHandlingiPhoneOS/GestureRecognizer_basics/GestureRecognizer_basics.html
