### ISSUE TITLE
'interfaceOrientation' is deprecated: first deprecated in iOS 8.0 

### ISSUE THREAD

**Issue by calebkleveter** [nmattisson/DropdownMenu#25]
I added the files to my project manually, and I get an issue warning in 'DropdownMenuController.m' in the offset method on line 194 saying "'interfaceOrientation' is deprecated: first deprecated in iOS 8.0 ", what do I use instead?

```objective-c
-(CGFloat)offset {
    return UIInterfaceOrientationIsLandscape(self.interfaceOrientation) ? 20.0f : 0.0f;
}                                                          ^Error here
```

**Comment by nsnutella** [comment]
Hi @calebkleveter 

You can use `[UIApplication sharedApplication].statusBarOrientation`.

Apple now recommends a method called `viewWillTransitionToSize:withTransitionCoordinator:`.

Hope that can helps ;)
Many Regards

**Comment by calebkleveter** [comment]
So, will `return [UIApplication sharedApplication].statusBarOrientation;` do the same thing as `return UIInterfaceOrientationIsLandscape(self.interfaceOrientation) ? 20.0f : 0.0f;`?

**Comment by nsnutella** [comment]
No, instead of `self.interfaceOrientation`, you should use `[UIApplication sharedApplication].statusBarOrientation`.

Like this
```
-(CGFloat)offset {
    UIInterfaceOrientation orientation = [UIApplication sharedApplication].statusBarOrientation;
    return UIInterfaceOrientationIsLandscape(orientation) ? 20.0f : 0.0f;
}
```

**Comment by calebkleveter** [comment]
Ah, that makes sense. Thanks!
