### ISSUE TITLE
Can I create a Swift version of this repository?

### ISSUE THREAD

**Issue by calebkleveter** [nmattisson/DropdownMenu#27]
@nmattisson, I think it is fine if I create a Swift version of this repository, but I thought I would ask first.

**Comment by nmattisson** [comment]
Of course! Knock yourself out. :+1:

**Comment by calebkleveter** [comment]
[Here is the beta version](https://github.com/calebkleveter/SwiftDropdownMenu), I got it to a release point early yesterday afternoon.
